<?xml version="1.0" encoding="utf-8"?><Database Name="VisaLicenses" Class="LicenseDbClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VisaLicenses.mssql.somee.com;Initial Catalog=VisaLicenses;Persist Security Info=True;User ID=visahelper_SQLLogin_1" SettingsObjectName="Visa.License.Properties.Settings" SettingsPropertyName="VisaLicensesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_License" Member="Licenses" ThisKey="ID" OtherKey="CustomerID" Type="License" />
    </Type>
  </Table>
  <Table Name="dbo.Licenses" Member="Licenses">
    <Type Name="License">
      <Column Name="Guid" Type="System.String" DbType="NVarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PcName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_License" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>