<?xml version="1.0" encoding="utf-8"?><Database Name="LicenseDB" Class="ModelLicenseDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mssql2.gear.host;Initial Catalog=licensetest;User ID=licensetest;MultipleActiveResultSets=True" SettingsObjectName="Visa.License.Properties.Settings" SettingsPropertyName="LicenseDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Instances" Member="Instances">
    <Type Name="Instance">
      <Column Name="Guid" Type="System.String" DbType="NVarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PcName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>