//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visa.Resources.uk_UA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class uk_UA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal uk_UA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visa.Resources.uk_UA.uk-UA", typeof(uk_UA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатково.
        /// </summary>
        public static string ApplicationMenu_Caption {
            get {
                return ResourceManager.GetString("ApplicationMenu_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка недоступна. Натисніть
        ///&quot;OK&quot; - постійно провіряти доступність сайту,
        ///або &quot;Скасувати&quot; - щоб відмінити..
        /// </summary>
        public static string AvailabilityError_Message {
            get {
                return ResourceManager.GetString("AvailabilityError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Імпорт клієнтів.
        /// </summary>
        public static string BarButtonItemImport_Caption {
            get {
                return ResourceManager.GetString("BarButtonItemImport_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string BarButtonItemSetup_Caption {
            get {
                return ResourceManager.GetString("BarButtonItemSetup_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string ButtonCancel_Text {
            get {
                return ResourceManager.GetString("ButtonCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити процес.
        /// </summary>
        public static string ButtonCancelAction_Text {
            get {
                return ResourceManager.GetString("ButtonCancelAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string ButtonOk_Text {
            get {
                return ResourceManager.GetString("ButtonOk_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустити реєстрацію.
        /// </summary>
        public static string ButtonRegistry_Text {
            get {
                return ResourceManager.GetString("ButtonRegistry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string colBirthday {
            get {
                return ResourceManager.GetString("colBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К-ть дітей вписаний у паспорт батьків.
        /// </summary>
        public static string colChildsCount {
            get {
                return ResourceManager.GetString("colChildsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата закінчення терміну дії паспорту.
        /// </summary>
        public static string colEndPassportDate {
            get {
                return ResourceManager.GetString("colEndPassportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string colLastName {
            get {
                return ResourceManager.GetString("colLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string colName {
            get {
                return ResourceManager.GetString("colName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № квитанції.
        /// </summary>
        public static string colNumberOfReceipt {
            get {
                return ResourceManager.GetString("colNumberOfReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість заявників.
        /// </summary>
        public static string colPeopleCount {
            get {
                return ResourceManager.GetString("colPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація З.
        /// </summary>
        public static string colRegistryFom {
            get {
                return ResourceManager.GetString("colRegistryFom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час реєстрації.
        /// </summary>
        public static string colRegistryTime {
            get {
                return ResourceManager.GetString("colRegistryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація До.
        /// </summary>
        public static string colRegistryTo {
            get {
                return ResourceManager.GetString("colRegistryTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата повернення.
        /// </summary>
        public static string colReturnData {
            get {
                return ResourceManager.GetString("colReturnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string colStatus {
            get {
                return ResourceManager.GetString("colStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата не відповідає діапазону 
        ///{0}.
        /// </summary>
        public static string DateIncorrect_Message {
            get {
                return ResourceManager.GetString("DateIncorrect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В програмі була згенерована помилка 
        ///яка не була належним чином оброблена. 
        ///Будь-ласка пришліть детальний опис 
        ///ваших дій  і опис помилки що є внизу..
        /// </summary>
        public static string ExceptionHanler_Text {
            get {
                return ResourceManager.GetString("ExceptionHanler_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string ExceptionHanler_Title {
            get {
                return ResourceManager.GetString("ExceptionHanler_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрацію завершено, 
        ///випевніть капчу і виберіть дату.
        /// </summary>
        public static string FillCaptchaAndComplete {
            get {
                return ResourceManager.GetString("FillCaptchaAndComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Випевніть капчу і натисніть ТУТ..
        /// </summary>
        public static string FillCaptchaAndPress {
            get {
                return ResourceManager.GetString("FillCaptchaAndPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей ключ уже використовуєтся 
        ///іншим комп&apos;ютером.
        /// </summary>
        public static string Key_Used {
            get {
                return ResourceManager.GetString("Key_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL для провірки доступності сайту.
        /// </summary>
        public static string lblAvailabilityUrl {
            get {
                return ResourceManager.GetString("lblAvailabilityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна команди.
        /// </summary>
        public static string lblCancelGroup {
            get {
                return ResourceManager.GetString("lblCancelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані клієнтів.
        /// </summary>
        public static string lblClientDataGroup {
            get {
                return ResourceManager.GetString("lblClientDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрити бравзер після закінчення?.
        /// </summary>
        public static string lblCloseBrowser {
            get {
                return ResourceManager.GetString("lblCloseBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервісний центр:.
        /// </summary>
        public static string lblServiceCenter {
            get {
                return ResourceManager.GetString("lblServiceCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Візова категорія:.
        /// </summary>
        public static string lblVisaCategory {
            get {
                return ResourceManager.GetString("lblVisaCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть Національніть-.
        /// </summary>
        public static string Nationality_NullText {
            get {
                return ResourceManager.GetString("Nationality_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Національність.
        /// </summary>
        public static string Nationality_Text {
            get {
                return ResourceManager.GetString("Nationality_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка виберіть Excel документ 
        ///з даними по шаблону.
        /// </summary>
        public static string OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Польський візовий центр доступний.
        /// </summary>
        public static string PageAvailable {
            get {
                return ResourceManager.GetString("PageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт недоступний.
        /// </summary>
        public static string PageNotAvailable {
            get {
                return ResourceManager.GetString("PageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password_Text {
            get {
                return ResourceManager.GetString("Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Час Реєстрації-.
        /// </summary>
        public static string RegistryTime_NullText {
            get {
                return ResourceManager.GetString("RegistryTime_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторно запускати при помилці.
        /// </summary>
        public static string RepeatIfCrash_Text {
            get {
                return ResourceManager.GetString("RepeatIfCrash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результати пошуку.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер не відповідає. Щоб поторити
        /// спробу запустіть перевірку знову!.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть ППВА-.
        /// </summary>
        public static string ServiceCenter_NullText {
            get {
                return ResourceManager.GetString("ServiceCenter_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть Статус-.
        /// </summary>
        public static string Status_NullText {
            get {
                return ResourceManager.GetString("Status_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string ToggleSwitch_OffText {
            get {
                return ResourceManager.GetString("ToggleSwitch_OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string ToggleSwitch_OnText {
            get {
                return ResourceManager.GetString("ToggleSwitch_OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка випевніть візовий ценрт
        /// і візову категорію.
        /// </summary>
        public static string ValidationError_Message_FirstPart {
            get {
                return ResourceManager.GetString("ValidationError_Message_FirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це поле повинно містити в собі значення.
        /// </summary>
        public static string ValidationError_Message_NullText {
            get {
                return ResourceManager.GetString("ValidationError_Message_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-ласка перевірте введені вами дані
        /// у таблиці та випевніть візовий центр.
        /// </summary>
        public static string ValidationError_Message_SecondPart {
            get {
                return ResourceManager.GetString("ValidationError_Message_SecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валідація не пройдена.
        /// </summary>
        public static string ValidationError_Title {
            get {
                return ResourceManager.GetString("ValidationError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Оберіть візову категорію-.
        /// </summary>
        public static string VisaCategory_NullText {
            get {
                return ResourceManager.GetString("VisaCategory_NullText", resourceCulture);
            }
        }
    }
}
